import { MAXIMUM_RATING } from "../components/RatingDisplayer/RatingDisplayer";

const FONT_DATA: Array<Font> = [
    { family: "Times New Roman", author: "Stanley Morison & Victor Lardent" },
    { family: "Arial", author: "Robin Nicholas & Patricia Macdonald" },
    { family: "Courier New", author: "Adrian Frutiger" },
    { family: "Verdana", author: "Matthew Carter & Robin Biggar" },
    { family: "Georgia", author: "Matthew Carter & Cheryl Hess" },
    { family: "Comic Sans MS", author: "Vincent Connare" },
    { family: "Trebuchet MS", author: "Vincent Connare" },
    { family: "Symbol", author: "Microsoft Corporation" },
    { family: "Webdings", author: "Vincent Connare" },
    { family: "Wingdings", author: "Microsoft Corporation" },
    { family: "Lucida Console", author: "Charles Bigelow & Kris Holmes" },
    { family: "Lucida Sans Unicode", author: "Charles Bigelow & Kris Holmes" },
    { family: "Palatino Linotype", author: "Hermann Zapf" },
    { family: "Tahoma", author: "Matthew Carter & Henri Leconte" },
    { family: "MS Sans Serif", author: "Microsoft Corporation" },
    { family: "MS Serif", author: "Microsoft Corporation" },
    { family: "Cambria", author: "Robin Nicholas & Patricia Macdonald" },
    { family: "Calibri", author: "Lucas de Groot" },
    { family: "Consolas", author: "Charles Bigelow & Kris Holmes" },
    { family: "Constantia", author: "Carol Twombly" },
    { family: "Corsiva", author: "David Leclereq" },
    { family: "Garamond", author: "Claude Garamond" },
    { family: "agency FB", author: "Susan Kare" },
    { family: "Algerian", author: "Monotype Drawing Office" },
    { family: "Arial Black", author: "Robin Nicholas & Patricia Macdonald" },
    { family: "Arial Narrow", author: "Robin Nicholas & Patricia Macdonald" },
    { family: "Bodoni MT Bold", author: "Giambattista Bodoni" },
    { family: "Book Antiqua", author: "Monotype Drawing Office" },
    { family: "Bradley Hand ITC", author: "Carol Twombly" },
    { family: "Century Gothic", author: "Morris Fuller Benton" },
    { family: "Century Schoolbook", author: "Morris Fuller Benton" },
    { family: "Engravers MT", author: "Luc Devroye" },
    { family: "Franklin Gothic Heavy", author: "Morris Fuller Benton" },
    { family: "Frutiger Linotype", author: "Adrian Frutiger" },
    { family: "Gill Sans MT", author: "Eric Gill" },
    { family: "Impact", author: "Geoffrey Lee" },
    { family: "Marlett", author: "Microsoft Corporation" },
    { family: "MS Gothic", author: "The Monotype Corporation" },
    { family: "MS Mincho", author: "The Monotype Corporation" },
    { family: "MV Boli", author: "Robert Michaelson Vandals" },
    { family: "Plantagenet Cherokee", author: "Monotype Drawing Office" },
    { family: "Rockwell Extra Bold", author: "W.A. Dwiggins" },
    { family: "Script MT Bold", author: "Susan Williford" },
    { family: "Small Fonts", author: "Microsoft Corporation" },
    { family: "Symbol", author: "Microsoft Corporation" },
    { family: "System", author: "Microsoft Corporation" },
    { family: "Times New Roman Bold", author: "Stanley Morison & Victor Lardent" },
    { family: "Trebuchet MS Bold", author: "Vincent Connare" },
    { family: "Verdana Bold", author: "Matthew Carter & Robin Biggar" },
    { family: "Webdings", author: "Vincent Connare" },
].map(font => ({
    ...font,
    rating: ~~(Math.random() * (MAXIMUM_RATING + 1)),
}));

export default FONT_DATA;